### ISSUE TITLE
Help with dependent versions

### ISSUE THREAD

**Issue by WangBJ233** [NieXiuping/WIML#1]
Hello author, thank you for your outstanding contribution. I'm having trouble reproducing your project with an installer error, can you please give me the version of the dependencies required for the project?

**Comment by NieXiuping** [comment]
The dependencies I used:  
torch 1.10.0+cu113 
torchvision 0.11.1+cu113
python 3.9.7

I hope this could help you. Feel free to ask any questions you have.
